# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "tomy0000000"
    commit-message:
      prefix: "⬆️ bump: "
    target-branch: "develop"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "tomy0000000"
    commit-message:
      prefix: "⬆️ bump: "
    target-branch: "develop"
