# https://pre-commit.ci/#configuration
ci:
  autoupdate_branch: "develop"
  autoupdate_commit_msg: "🎛 ci: pre-commit autoupdate"
# https://pre-commit.com/#pre-commit-configyaml---top-level
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  # # TODO: Turn me back on someday
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.14.1"
  #   hooks:
  #     - id: mypy
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.3"
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
