services:
  k-backend:
    command: "uvicorn k_backend.main:app --host 0.0.0.0 --port 8000"
    container_name: "k_backend_app"
    depends_on:
      - "postgres"
    env_file:
      - "instance/production.env"
    image: "tomy0000000/k-backend"
    restart: "always"
    volumes:
      - "./instance:/usr/src/k-backend/instance"
  postgres:
    container_name: "k_backend_db"
    env_file:
      - "instance/production.env"
    image: "postgres:14"
    restart: "always"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

volumes:
  postgres_data:
