services:
  kayman:
    container_name: "kayman-app"
    depends_on:
      - "db"
    env_file:
      - "instance/.env"
    image: "tomy0000000/kayman"
    restart: "always"
    volumes:
      - "./instance:/usr/src/kayman/instance"

  db:
    container_name: "kayman-db"
    env_file:
      - "instance/.env"
    image: "postgres:17"
    restart: "always"
    volumes:
      - "data:/var/lib/postgresql/data"

volumes:
  data:
