services:
  api:
    container_name: "k-backend-api"
    depends_on:
      - "db"
    env_file:
      - "instance/.env"
    image: "tomy0000000/k-backend"
    restart: "always"
    volumes:
      - "./instance:/usr/src/k-backend/instance"

  db:
    container_name: "k-backend-db"
    env_file:
      - "instance/.env"
    image: "postgres:17"
    restart: "always"
    volumes:
      - "data:/var/lib/postgresql/data"

volumes:
  data:
