[tool.poetry]
name = "k-backend"
version = "0.6.0"
description = "The backend API server of K"
authors = ["Tomy Hsieh <tomy0000000@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.78.0"
SQLAlchemy = "1.4.35"
pydantic = "^1.9.1"
sqlmodel = "^0.0.6"
uvicorn = {extras = ["standard"], version = "^0.17.6"}
psycopg2 = "^2.9.3"
alembic = "^1.7.7"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
python-multipart = "^0.0.5"
loguru = "^0.6.0"
tzdata = "^2022.1"
simplejson = "^3.17.6"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
isort = "^5.10.1"
ipython = "^8.4.0"
flake8 = "^4.0.1"
mypy = "^0.960"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
