"""Switch from float to decimal

Revision ID: 5a4906bfb3bd
Revises: b57d9713593a
Create Date: 2022-06-10 15:12:21.297924

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5a4906bfb3bd"
down_revision = "b57d9713593a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("account", "balance", existing_type=sa.NUMERIC(), nullable=False)
    op.alter_column(
        "payment",
        "total",
        existing_type=sa.FLOAT(precision=53),
        type_=sa.NUMERIC(),
    )
    op.alter_column(
        "payment_entry",
        "amount",
        existing_type=sa.FLOAT(precision=53),
        type_=sa.NUMERIC(),
    )
    op.alter_column(
        "transaction",
        "amount",
        existing_type=sa.FLOAT(precision=53),
        type_=sa.NUMERIC(),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("account", "balance", existing_type=sa.NUMERIC(), nullable=True)
    op.alter_column(
        "payment",
        "total",
        existing_type=sa.NUMERIC(),
        type_=sa.FLOAT(precision=53),
    )
    op.alter_column(
        "payment_entry",
        "amount",
        existing_type=sa.NUMERIC(),
        type_=sa.FLOAT(precision=53),
    )
    op.alter_column(
        "transaction",
        "amount",
        existing_type=sa.NUMERIC(),
        type_=sa.FLOAT(precision=53),
    )
    # ### end Alembic commands ###
