"""Exchange Payment Type

Revision ID: 7c2873a67659
Revises: d8b620575729
Create Date: 2022-06-11 03:10:39.262536

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7c2873a67659"
down_revision = "d8b620575729"
branch_labels = None
depends_on = None

old_enum = sa.Enum("Expense", "Income", "Transfer", name="paymentcategory")
new_enum = sa.Enum("Expense", "Income", "Transfer", "Exchange", name="paymenttype")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    new_enum.create(op.get_bind(), checkfirst=False)
    op.alter_column(
        "payment",
        "category",
        existing_type=old_enum,
        type_=new_enum,
        new_column_name="type",
        postgresql_using="category::text::paymenttype",
    )
    old_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    old_enum.create(op.get_bind(), checkfirst=False)
    op.alter_column(
        "payment",
        "type",
        existing_type=new_enum,
        type_=old_enum,
        new_column_name="category",
        postgresql_using="type::text::paymentcategory",
    )
    new_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
