"""Payment Service Provider Relationship

Revision ID: 90e77fb7e8ff
Revises: a02d9bdab5c5
Create Date: 2022-06-30 10:07:29.610859

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "90e77fb7e8ff"
down_revision = "a02d9bdab5c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("psp_id", sa.Integer(), nullable=True))
    op.add_column(
        "transaction", sa.Column("psp_reconcile", sa.Boolean(), nullable=False)
    )
    op.create_foreign_key(
        "fk_transaction_psp_id_payment_service_providers",
        "transaction",
        "payment_service_providers",
        ["psp_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_transaction_psp_id_payment_service_providers",
        "transaction",
        type_="foreignkey",
    )
    op.drop_column("transaction", "psp_reconcile")
    op.drop_column("transaction", "psp_id")
    # ### end Alembic commands ###
