"""Transaction reconcile

Revision ID: b6b977bf8dd2
Revises: c48d26a61bef
Create Date: 2022-06-29 17:06:18.307077

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b6b977bf8dd2"
down_revision = "c48d26a61bef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transaction", sa.Column("reconcile", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "reconcile")
    # ### end Alembic commands ###
