"""Subcategory and disable

Revision ID: e4e019712d5d
Revises: b6b977bf8dd2
Create Date: 2022-06-30 01:06:11.200339

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e4e019712d5d"
down_revision = "b6b977bf8dd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("category", sa.Column("disabled", sa.Boolean(), nullable=False))
    op.add_column("category", sa.Column("parent_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_category_parent_id_category", "category", "category", ["parent_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_category_parent_id_category", "category", type_="foreignkey")
    op.drop_column("category", "parent_id")
    op.drop_column("category", "disabled")
    # ### end Alembic commands ###
