// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Item struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewItem struct {
	Name string `json:"name"`
}

type NewPaymentAccount struct {
	Name string `json:"name"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type PaymentAccount struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Transaction struct {
	ID        string            `json:"id"`
	Timestamp time.Time         `json:"timestamp"`
	Accounts  []*PaymentAccount `json:"accounts"`
	Items     []*Item           `json:"items"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
