"""Timezone support

Revision ID: f4a2b4c19de0
Revises: 3e2b14dec671
Create Date: 2022-05-30 11:37:20.922466

"""

import sqlalchemy as sa
from alembic import op

from kayman.schemas._custom_types import SATimezone

# revision identifiers, used by Alembic.
revision = "f4a2b4c19de0"
down_revision = "3e2b14dec671"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payment", sa.Column("timezone", SATimezone(), nullable=False))
    op.add_column("transaction", sa.Column("timezone", SATimezone(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transaction", "timezone")
    op.drop_column("payment", "timezone")
    # ### end Alembic commands ###
